#!/bin/bash

#brew install jq
#brew install wget
#brew install go
#go get github.com/jehiah/json2csv

mkdir weatherjsons
cd weatherjsons

YEAR_today=`date +%Y`
MONTH_today=`date +%m`
DAY_today=`date +%d`



wbans="94846 14855 04807 14819 94866 04831"
for wban in $wbans; do
for year in `seq $YEAR_today $YEAR_today`; do
for month in `seq $MONTH_today $MONTH_today`; do 

priorMonth=`date -jf  "%Y%m%d" -v-30d $year$month$DAY_today +"%m"`
priorYear=`date -jf  "%Y%m%d" -v-30d $year$month$DAY_today +"%Y"`
priorDay=`date -jf  "%Y%m%d" -v-30d $year$month$DAY_today +"%d"`

url="http://plenar.io/v1/api/weather/hourly/?wban_code=$wban&datetime__ge=$priorYear-$priorMonth-$priorDay&datetime__lt=$year-$month-$DAY_today"
echo $url
curl -o $wban.$year.$month.json $url
sleep 5
done
done
done

wbans="94846 14855 04807 14819 94866 04831"
for wban in $wbans; do
for year in `seq $YEAR_today $YEAR_today`; do
for month in `seq $previousMonth $MONTH_today`; do 

~/.local/bin/jq -c '.objects[0].observations[]' $wban.$year.$month.json > $wban.$year.$month.obs.json
done
done
done

######make sure you are in ONYL a weatherjsons folder before you run following command— deletes all files below 1k within folder
find . -size -1k -name "*.json" -delete

echo "wind_speed,dt,relative_humidity,hourly_precip,drybulb_fahrenheit,wban_code" > ChicagoWeather_Update_.csv

wbans="94846 14855 04807 14819 94866 04831"
for wban in $wbans; do
for year in `seq $YEAR_today $YEAR_today`; do
for month in `seq $previousMonth $MONTH_today`; do 
file=$wban.$year.$month.obs.json
if [ -f $file ];then
~/gocode/bin/json2csv -i $file -k wind_speed,datetime,relative_humidity,hourly_precip,drybulb_fahrenheit,wban_code >> ChicagoWeather_Update_.csv
fi
done
done
done
mv ChicagoWeather_Update_.csv ..




